/*
 * Created on 10 8월 2017 ( Time 14:44:37 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.trams.hello.bean;

import java.io.Serializable;

import java.util.Date;

/**
 * Java bean for 'CompanyUserVoucherHistory' entity
 * 
 * @author Telosys Tools
 *
 */
public class CompanyUserVoucherHistory implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    // DB : id INT 
    private Integer id;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    // DB : business_sub_id INT 
    private Integer businessSubId;

    // DB : user_id INT 
    private Integer userId;

    // DB : aimmed_user_id VARCHAR 
    private String aimmedUserId;

    // DB : create_date DATETIME 
    private Date createDate;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }

    public Integer getId() {
        return this.id;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setBusinessSubId( Integer businessSubId ) {
        this.businessSubId = businessSubId;
    }
    public Integer getBusinessSubId() {
        return this.businessSubId;
    }

    public void setUserId( Integer userId ) {
        this.userId = userId;
    }
    public Integer getUserId() {
        return this.userId;
    }

    public void setAimmedUserId( String aimmedUserId ) {
        this.aimmedUserId = aimmedUserId;
    }
    public String getAimmedUserId() {
        return this.aimmedUserId;
    }

    public void setCreateDate( Date createDate ) {
        this.createDate = createDate;
    }
    public Date getCreateDate() {
        return this.createDate;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(id);
        sb.append("|");
        sb.append(businessSubId);
        sb.append("|");
        sb.append(userId);
        sb.append("|");
        sb.append(aimmedUserId);
        sb.append("|");
        sb.append(createDate);
        return sb.toString(); 
    } 


}
