/*
 * Created on 7 Apr 2017 ( Time 17:33:11 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.trams.hello.bean;

import java.io.Serializable;
import java.util.Date;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;
@DynamicInsert
@DynamicUpdate
public class Message implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    private Integer id;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @NotNull
    private Integer sendUserId;

    @NotNull
    @Size( min = 1, max = 65535 )
    private String content;


    private Integer typeUser;

    @NotNull
    private Date sendDate;


    private Date recieveDate;


    private Date createDate;


    private Date updateDate;

    
    private Short isDelete;

    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }

    public Integer getId() {
        return this.id;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    
    
    public void setSendUserId( Integer sendUserId ) {
        this.sendUserId = sendUserId;
    }
    public Short getIsDelete() {
		return isDelete;
	}

	public void setIsDelete(Short isDelete) {
		this.isDelete = isDelete;
	}

	public Integer getSendUserId() {
        return this.sendUserId;
    }

    public void setContent( String content ) {
        this.content = content;
    }
    public String getContent() {
        return this.content;
    }

    public void setTypeUser( Integer typeUser ) {
        this.typeUser = typeUser;
    }
    public Integer getTypeUser() {
        return this.typeUser;
    }

    public void setSendDate( Date sendDate ) {
        this.sendDate = sendDate;
    }
    public Date getSendDate() {
        return this.sendDate;
    }

    public void setRecieveDate( Date recieveDate ) {
        this.recieveDate = recieveDate;
    }
    public Date getRecieveDate() {
        return this.recieveDate;
    }

    public void setCreateDate( Date createDate ) {
        this.createDate = createDate;
    }
    public Date getCreateDate() {
        return this.createDate;
    }

    public void setUpdateDate( Date updateDate ) {
        this.updateDate = updateDate;
    }
    public Date getUpdateDate() {
        return this.updateDate;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(id);
        sb.append("|");
        sb.append(sendUserId);
        // attribute 'content' not usable (type = String Long Text)
        sb.append("|");
        sb.append(typeUser);
        sb.append("|");
        sb.append(sendDate);
        sb.append("|");
        sb.append(recieveDate);
        sb.append("|");
        sb.append(createDate);
        sb.append("|");
        sb.append(updateDate);
        return sb.toString(); 
    } 


}
