/*
 * Created on 1 thg 12 2016 ( Time 15:28:37 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.trams.hello.bean.jpa;
import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * Composite primary key for entity "CounselorFieldEntity" ( stored in table "counselor_field" )
 *
 * @author Telosys Tools Generator
 *
 */
 @Embeddable
public class CounselorFieldEntityKey implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY KEY ATTRIBUTES 
    //----------------------------------------------------------------------
    @Column(name="counselor_id", nullable=false)
    private Integer    counselorId  ;
    @Column(name="counselor_field_id", nullable=false)
    private Integer    counselorFieldId ;

    //----------------------------------------------------------------------
    // CONSTRUCTORS
    //----------------------------------------------------------------------
    public CounselorFieldEntityKey() {
        super();
    }

    public CounselorFieldEntityKey( Integer counselorId, Integer counselorFieldId ) {
        super();
        this.counselorId = counselorId ;
        this.counselorFieldId = counselorFieldId ;
    }
    
    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR KEY FIELDS
    //----------------------------------------------------------------------
    public void setCounselorId( Integer value ) {
        this.counselorId = value;
    }
    public Integer getCounselorId() {
        return this.counselorId;
    }

    public void setCounselorFieldId( Integer value ) {
        this.counselorFieldId = value;
    }
    public Integer getCounselorFieldId() {
        return this.counselorFieldId;
    }


    //----------------------------------------------------------------------
    // equals METHOD
    //----------------------------------------------------------------------
	public boolean equals(Object obj) { 
		if ( this == obj ) return true ; 
		if ( obj == null ) return false ;
		if ( this.getClass() != obj.getClass() ) return false ; 
		CounselorFieldEntityKey other = (CounselorFieldEntityKey) obj; 
		//--- Attribute counselorId
		if ( counselorId == null ) { 
			if ( other.counselorId != null ) 
				return false ; 
		} else if ( ! counselorId.equals(other.counselorId) ) 
			return false ; 
		//--- Attribute counselorFieldId
		if ( counselorFieldId == null ) { 
			if ( other.counselorFieldId != null ) 
				return false ; 
		} else if ( ! counselorFieldId.equals(other.counselorFieldId) ) 
			return false ; 
		return true; 
	} 


    //----------------------------------------------------------------------
    // hashCode METHOD
    //----------------------------------------------------------------------
	public int hashCode() { 
		final int prime = 31; 
		int result = 1; 
		
		//--- Attribute counselorId
		result = prime * result + ((counselorId == null) ? 0 : counselorId.hashCode() ) ; 
		//--- Attribute counselorFieldId
		result = prime * result + ((counselorFieldId == null) ? 0 : counselorFieldId.hashCode() ) ; 
		
		return result; 
	} 


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() {
		StringBuffer sb = new StringBuffer(); 
		sb.append(counselorId); 
		sb.append("|"); 
		sb.append(counselorFieldId); 
        return sb.toString();
    }
}
