/*
 * Created on 29 Apr 2017 ( Time 11:01:44 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.trams.hello.bean.jpa;
import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * Composite primary key for entity "CounselorFieldTempEntity" ( stored in table "counselor_field_temp" )
 *
 * @author Telosys Tools Generator
 *
 */
 @Embeddable
public class CounselorFieldTempEntityKey implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY KEY ATTRIBUTES 
    //----------------------------------------------------------------------
    @Column(name="counselor_temp_id", nullable=false)
    private Integer    counselorTempId ;
    @Column(name="counselor_field_id", nullable=false)
    private Integer    counselorFieldId ;

    //----------------------------------------------------------------------
    // CONSTRUCTORS
    //----------------------------------------------------------------------
    public CounselorFieldTempEntityKey() {
        super();
    }

    public CounselorFieldTempEntityKey( Integer counselorTempId, Integer counselorFieldId ) {
        super();
        this.counselorTempId = counselorTempId ;
        this.counselorFieldId = counselorFieldId ;
    }
    
    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR KEY FIELDS
    //----------------------------------------------------------------------
    public void setCounselorTempId( Integer value ) {
        this.counselorTempId = value;
    }
    public Integer getCounselorTempId() {
        return this.counselorTempId;
    }

    public void setCounselorFieldId( Integer value ) {
        this.counselorFieldId = value;
    }
    public Integer getCounselorFieldId() {
        return this.counselorFieldId;
    }


    //----------------------------------------------------------------------
    // equals METHOD
    //----------------------------------------------------------------------
	public boolean equals(Object obj) { 
		if ( this == obj ) return true ; 
		if ( obj == null ) return false ;
		if ( this.getClass() != obj.getClass() ) return false ; 
		CounselorFieldTempEntityKey other = (CounselorFieldTempEntityKey) obj; 
		//--- Attribute counselorTempId
		if ( counselorTempId == null ) { 
			if ( other.counselorTempId != null ) 
				return false ; 
		} else if ( ! counselorTempId.equals(other.counselorTempId) ) 
			return false ; 
		//--- Attribute counselorFieldId
		if ( counselorFieldId == null ) { 
			if ( other.counselorFieldId != null ) 
				return false ; 
		} else if ( ! counselorFieldId.equals(other.counselorFieldId) ) 
			return false ; 
		return true; 
	} 


    //----------------------------------------------------------------------
    // hashCode METHOD
    //----------------------------------------------------------------------
	public int hashCode() { 
		final int prime = 31; 
		int result = 1; 
		
		//--- Attribute counselorTempId
		result = prime * result + ((counselorTempId == null) ? 0 : counselorTempId.hashCode() ) ; 
		//--- Attribute counselorFieldId
		result = prime * result + ((counselorFieldId == null) ? 0 : counselorFieldId.hashCode() ) ; 
		
		return result; 
	} 


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() {
		StringBuffer sb = new StringBuffer(); 
		sb.append(counselorTempId); 
		sb.append("|"); 
		sb.append(counselorFieldId); 
        return sb.toString();
    }
}
