/*
 * Created on 22 Jun 2017 ( Time 17:36:05 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package org.trams.hello.bean.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

/**
 * Persistent class for entity stored in table "login_history"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="login_history", catalog="hello" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="LoginHistoryEntity.countAll", query="SELECT COUNT(x) FROM LoginHistoryEntity x" )
} )
@DynamicInsert
@DynamicUpdate
public class LoginHistoryEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Long       id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="device_id", length=200)
    private String     deviceId     ;

    @Column(name="user_id", nullable=false)
    private Integer    userId       ;

    @Column(name="gender")
    private Short      gender       ;

    @Column(name="age")
    private Short      age          ;

    @Column(name="type_user")
    private Short      typeUser     ;

    @Temporal(TemporalType.DATE)
    @Column(name="create_date")
    private Date       createDate   ;

    @Column(name="type_os", length=50)
    private String     typeOs       ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="login_last")
    private Date       loginLast    ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public LoginHistoryEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Long id ) {
        this.id = id ;
    }
    public Long getId() {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : device_id ( VARCHAR ) 
    public void setDeviceId( String deviceId ) {
        this.deviceId = deviceId;
    }
    public String getDeviceId() {
        return this.deviceId;
    }

    //--- DATABASE MAPPING : user_id ( INT ) 
    public void setUserId( Integer userId ) {
        this.userId = userId;
    }
    public Integer getUserId() {
        return this.userId;
    }

    //--- DATABASE MAPPING : gender ( SMALLINT ) 
    public void setGender( Short gender ) {
        this.gender = gender;
    }
    public Short getGender() {
        return this.gender;
    }

    //--- DATABASE MAPPING : age ( SMALLINT ) 
    public void setAge( Short age ) {
        this.age = age;
    }
    public Short getAge() {
        return this.age;
    }

    //--- DATABASE MAPPING : type_user ( SMALLINT ) 
    public void setTypeUser( Short typeUser ) {
        this.typeUser = typeUser;
    }
    public Short getTypeUser() {
        return this.typeUser;
    }

    //--- DATABASE MAPPING : create_date ( DATE ) 
    public void setCreateDate( Date createDate ) {
        this.createDate = createDate;
    }
    public Date getCreateDate() {
        return this.createDate;
    }

    //--- DATABASE MAPPING : type_os ( VARCHAR ) 
    public void setTypeOs( String typeOs ) {
        this.typeOs = typeOs;
    }
    public String getTypeOs() {
        return this.typeOs;
    }

    //--- DATABASE MAPPING : login_last ( DATETIME ) 
    public void setLoginLast( Date loginLast ) {
        this.loginLast = loginLast;
    }
    public Date getLoginLast() {
        return this.loginLast;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(id);
        sb.append("]:"); 
        sb.append(deviceId);
        sb.append("|");
        sb.append(userId);
        sb.append("|");
        sb.append(gender);
        sb.append("|");
        sb.append(age);
        sb.append("|");
        sb.append(typeUser);
        sb.append("|");
        sb.append(createDate);
        sb.append("|");
        sb.append(typeOs);
        sb.append("|");
        sb.append(loginLast);
        return sb.toString(); 
    } 

}
