/*
 * Created on 21 Apr 2017 ( Time 14:57:37 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package org.trams.hello.bean.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

/**
 * Persistent class for entity stored in table "test_result"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="test_result", catalog="hello" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="TestResultEntity.countAll", query="SELECT COUNT(x) FROM TestResultEntity x" )
} )
@DynamicInsert
@DynamicUpdate
public class TestResultEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private Integer    id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="point")
    private Float      point        ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="create_date")
    private Date       createDate   ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="update_date")
    private Date       updateDate   ;

	// "questionId" (column "question_id") is not defined by itself because used as FK in a link 
	// "answerId" (column "answer_id") is not defined by itself because used as FK in a link 
	// "selfDiagnosisAnswerId" (column "self_diagnosis_answer_id") is not defined by itself because used as FK in a link 
	// "userQuestionaireId" (column "user_questionaire_id") is not defined by itself because used as FK in a link 


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @ManyToOne
    @JoinColumn(name="self_diagnosis_answer_id", referencedColumnName="id")
    private SelfDiagnosisAnswerEntity selfDiagnosisAnswer;

    @ManyToOne
    @JoinColumn(name="answer_id", referencedColumnName="id")
    private AnswerEntity answer      ;

    @ManyToOne
    @JoinColumn(name="question_id", referencedColumnName="id")
    private QuestionEntity question    ;

    @ManyToOne
    @JoinColumn(name="user_questionaire_id", referencedColumnName="id")
    private UserQuestionaireEntity userQuestionaire;



    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public TestResultEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : point ( FLOAT ) 
    public void setPoint( Float point ) {
        this.point = point;
    }
    public Float getPoint() {
        return this.point;
    }

    //--- DATABASE MAPPING : create_date ( DATETIME ) 
    public void setCreateDate( Date createDate ) {
        this.createDate = createDate;
    }
    public Date getCreateDate() {
        return this.createDate;
    }

    //--- DATABASE MAPPING : update_date ( DATETIME ) 
    public void setUpdateDate( Date updateDate ) {
        this.updateDate = updateDate;
    }
    public Date getUpdateDate() {
        return this.updateDate;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setSelfDiagnosisAnswer( SelfDiagnosisAnswerEntity selfDiagnosisAnswer ) {
        this.selfDiagnosisAnswer = selfDiagnosisAnswer;
    }
    public SelfDiagnosisAnswerEntity getSelfDiagnosisAnswer() {
        return this.selfDiagnosisAnswer;
    }

    public void setAnswer( AnswerEntity answer ) {
        this.answer = answer;
    }
    public AnswerEntity getAnswer() {
        return this.answer;
    }

    public void setQuestion( QuestionEntity question ) {
        this.question = question;
    }
    public QuestionEntity getQuestion() {
        return this.question;
    }

    public void setUserQuestionaire( UserQuestionaireEntity userQuestionaire ) {
        this.userQuestionaire = userQuestionaire;
    }
    public UserQuestionaireEntity getUserQuestionaire() {
        return this.userQuestionaire;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(id);
        sb.append("]:"); 
        sb.append(point);
        sb.append("|");
        sb.append(createDate);
        sb.append("|");
        sb.append(updateDate);
        return sb.toString(); 
    } 

}
