/*
 * Created on 23 thg 11 2016 ( Time 13:38:12 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.trams.hello.business.service;

import java.util.List;
import java.util.Map;

import org.springframework.data.domain.Page;
import org.trams.hello.bean.Comment;
import org.trams.hello.bean.jpa.CommentEntity;

/**
 * Business Service Interface for entity Comment.
 */
public interface CommentService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	Comment findById( Integer id  ) ;

	/** 
	 * Loads all entities.
	 * @return all entities
	 */
	List<Comment> findAll();
	
	/**
	 * Loads entities in page number.
	 * @return entities
	 */

	Page<CommentEntity> findAll(Integer page);

	/**
	 * Count all entities
	 * @return Long
	 */
	Long countTotal();
	

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	Comment save(Comment entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	Comment update(Comment entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	Comment create(Comment entity);
	
	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete( Integer id );

	Page<CommentEntity> listPaging(Integer page,Integer size);
	
	Page<CommentEntity> listPagingBy_CounsolorId(Integer counsolorId, Integer page,Integer size);

	Page<CommentEntity> filter(Map<String, Object> params);

}
