/*
 * Created on 20 thg 1 2017 ( Time 10:09:40 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.trams.hello.business.service;

import java.util.List;

import org.springframework.data.domain.Page;
import org.trams.hello.bean.CounselorTemp;
import org.trams.hello.bean.jpa.CounselorTempEntity;

/**
 * Business Service Interface for entity CounselorTemp.
 */
public interface CounselorTempService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	CounselorTemp findById( Integer id  ) ;

	/** 
	 * Loads all entities.
	 * @return all entities
	 */
	List<CounselorTemp> findAll();
	
	/**
	 * Loads entities in page number.
	 * @return entities
	 */

	Page<CounselorTempEntity> findAll(Integer page);

	/**
	 * Count all entities
	 * @return Long
	 */
	Long countTotal();
	

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	CounselorTemp save(CounselorTemp entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	CounselorTemp update(CounselorTemp entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	CounselorTemp create(CounselorTemp entity);
	
	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete( Integer id );

	Page<CounselorTempEntity> listPaging(Integer page,Integer size);
	
	void update_isDelete(Integer id);

	CounselorTempEntity findOne(Integer id);

	Page<CounselorTempEntity> filter(Short[] status, String type, String key,Integer page, Integer size);
}
