/*
 * Created on 1 thg 12 2016 ( Time 11:42:56 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.trams.hello.business.service;

import java.util.List;

import org.springframework.data.domain.Page;
import org.trams.hello.bean.CounselorField;
import org.trams.hello.bean.jpa.CounselorFieldEntity;

/**
 * Business Service Interface for entity CounselorField.
 */
public interface CounselorFieldService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param counselorId
	 * @param counselorFieldId
	 * @return entity
	 */
	CounselorField findById( Integer counselorId, Integer counselorFieldId  ) ;

	/** 
	 * Loads all entities.
	 * @return all entities
	 */
	List<CounselorField> findAll();
	
	/**
	 * Loads entities in page number.
	 * @return entities
	 */

	Page<CounselorFieldEntity> findAll(Integer page);

	/**
	 * Count all entities
	 * @return Long
	 */
	Long countTotal();
	

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	CounselorField save(CounselorField entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	CounselorField update(CounselorField entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	CounselorField create(CounselorField entity);
	
	/**
	 * Deletes an entity using its Primary Key
	 * @param counselorId
	 * @param counselorFieldId
	 */
	void delete( Integer counselorId, Integer counselorFieldId );

	Page<CounselorFieldEntity> listPaging(Integer page,Integer size);
	
	List<CounselorFieldEntity> listBy_CounselorId(Integer counselorId);

	void deleteByCounselorId(Integer counselorId);
	
	List<Object> getCategoryNameBy_CouselorId(Integer counselorId);

}
