/*
 * Created on 8 thg 2 2017 ( Time 10:59:43 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.trams.hello.business.service;

import java.util.List;
import java.util.Map;

import org.springframework.data.domain.Page;
import org.trams.hello.bean.CounselingMemo;
import org.trams.hello.bean.jpa.CounselingMemoEntity;

/**
 * Business Service Interface for entity CounselingMemo.
 */
public interface CounselingMemoService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	CounselingMemo findById( Integer id  ) ;

	/** 
	 * Loads all entities.
	 * @return all entities
	 */
	List<CounselingMemo> findAll();
	
	/**
	 * Loads entities in page number.
	 * @return entities
	 */

	Page<CounselingMemoEntity> findAll(Integer page);

	/**
	 * Count all entities
	 * @return Long
	 */
	Long countTotal();
	

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	CounselingMemo save(CounselingMemo entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	CounselingMemo update(CounselingMemo entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	CounselingMemo create(CounselingMemo entity);
	
	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete( Integer id );

	Page<CounselingMemoEntity> listPaging(Integer page,Integer size);
	
	Page<CounselingMemoEntity> filter(Map<String, Object> params);

}
