/*
 * Created on 23 thg 11 2016 ( Time 13:38:12 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.trams.hello.business.service;

import java.util.List;

import org.springframework.data.domain.Page;
import org.trams.hello.bean.CounselingCenter;
import org.trams.hello.bean.jpa.CounselingCenterEntity;

/**
 * Business Service Interface for entity CounselingCenter.
 */
public interface CounselingCenterService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	CounselingCenter findById( Integer id  ) ;
	
	CounselingCenterEntity findOne( Integer id  ) ;

	/** 
	 * Loads all entities.
	 * @return all entities
	 */
	List<CounselingCenter> findAll();
	
	/**
	 * Loads entities in page number.
	 * @return entities
	 */

	Page<CounselingCenterEntity> findAll(Integer page);

	/**
	 * Count all entities
	 * @return Long
	 */
	Long countTotal();
	

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	CounselingCenter save(CounselingCenter entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	CounselingCenter update(CounselingCenter entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	CounselingCenter create(CounselingCenter entity);
	
	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete( Integer id );

	Page<CounselingCenterEntity> listPaging(Integer page,Integer size);
	
	void update_isDelete(Integer id);
	
	Page<CounselingCenterEntity> listPagingBy_StatusAndName(Integer status, String centerName, String orberBy, Integer page,Integer size);
	
	Page<CounselingCenterEntity> listPagingBy_Name(String centerName, String orderBy, Integer page,Integer size);

	Integer totalMoneyHaveNotPayForCounSelorCenter(Integer counselorCenterId);
	
	void updateCounselorFreelancerBy_CounselingCenter(Integer counselingCenterId);

}
