/*
 * Created on 11 thg 1 2017 ( Time 10:47:55 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.trams.hello.business.service;

import java.util.List;

import org.springframework.data.domain.Page;
import org.trams.hello.bean.Device;
import org.trams.hello.bean.jpa.DeviceEntity;

/**
 * Business Service Interface for entity Device.
 */
public interface DeviceService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	Device findById( Integer id  ) ;

	/** 
	 * Loads all entities.
	 * @return all entities
	 */
	List<Device> findAll();
	
	/**
	 * Loads entities in page number.
	 * @return entities
	 */

	Page<DeviceEntity> findAll(Integer page);

	/**
	 * Count all entities
	 * @return Long
	 */
	Long countTotal();
	

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	Device save(Device entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	Device update(Device entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	Device create(Device entity);
	
	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete( Integer id );

	Page<DeviceEntity> listPaging(Integer page,Integer size);

	/**
	 *
	 * @param userId
	 * @param uuid
	 * @param fcmToken
	 */
	void upsert(Integer userId, String uuid);
}
