/*
 * Created on 14 Mar 2017 ( Time 14:52:42 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.trams.hello.business.service;

import java.util.List;

import org.springframework.data.domain.Page;
import org.trams.hello.bean.MenuAdminLevel1;
import org.trams.hello.bean.jpa.MenuAdminLevel1Entity;

/**
 * Business Service Interface for entity MenuAdminLevel1.
 */
public interface MenuAdminLevel1Service { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	MenuAdminLevel1 findById( Integer id  ) ;

	/** 
	 * Loads all entities.
	 * @return all entities
	 */
	List<MenuAdminLevel1> findAll();
	
	/**
	 * Loads entities in page number.
	 * @return entities
	 */

	Page<MenuAdminLevel1Entity> findAll(Integer page);

	/**
	 * Count all entities
	 * @return Long
	 */
	Long countTotal();
	

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	MenuAdminLevel1 save(MenuAdminLevel1 entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	MenuAdminLevel1 update(MenuAdminLevel1 entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	MenuAdminLevel1 create(MenuAdminLevel1 entity);
	
	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete( Integer id );

	Page<MenuAdminLevel1Entity> listPaging(Integer page,Integer size);
	
	Page<MenuAdminLevel1Entity> findByName(String name, Integer page, Integer size);
	
	Page<MenuAdminLevel1Entity> getAdminMenu();


}
