/*
 * Created on 15 thg 12 2016 ( Time 10:18:19 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.trams.hello.business.service;

import java.util.Date;
import java.util.List;

import org.springframework.data.domain.Page;
import org.trams.hello.bean.ReportDaily;
import org.trams.hello.bean.jpa.ReportDailyEntity;

/**
 * Business Service Interface for entity ReportDaily.
 */
public interface ReportDailyService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	ReportDaily findById( Integer id  ) ;

	/** 
	 * Loads all entities.
	 * @return all entities
	 */
	List<ReportDaily> findAll();
	
	/**
	 * Loads entities in page number.
	 * @return entities
	 */

	Page<ReportDailyEntity> findAll(Integer page);

	/**
	 * Count all entities
	 * @return Long
	 */
	Long countTotal();
	

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	ReportDaily save(ReportDaily entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	ReportDaily update(ReportDaily entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	ReportDaily create(ReportDaily entity);
	
	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete( Integer id );

	Page<ReportDailyEntity> listPaging(Integer page,Integer size);
	
	List<ReportDailyEntity> findReportByCreateDate(Date date);

	ReportDaily findByCreateDate(Date date);
}
