/*
 * Created on 6 thg 1 2017 ( Time 17:05:04 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.trams.hello.business.service;

import java.util.List;

import org.springframework.data.domain.Page;
import org.trams.hello.bean.UserCertificate;
import org.trams.hello.bean.jpa.UserCertificateEntity;

/**
 * Business Service Interface for entity UserCertificate.
 */
public interface UserCertificateService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	UserCertificate findById( Integer id  ) ;

	/** 
	 * Loads all entities.
	 * @return all entities
	 */
	List<UserCertificate> findAll();
	
	/**
	 * Loads entities in page number.
	 * @return entities
	 */

	Page<UserCertificateEntity> findAll(Integer page);

	/**
	 * Count all entities
	 * @return Long
	 */
	Long countTotal();
	

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	UserCertificate save(UserCertificate entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	UserCertificate update(UserCertificate entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	UserCertificate create(UserCertificate entity);
	
	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete( Integer id );

	Page<UserCertificateEntity> listPaging(Integer page,Integer size);
	
	Page<UserCertificateEntity> listPagingByUserId( Integer page, Integer size, Integer userId);

	Page<UserCertificateEntity> findByName(String name, Integer page, Integer size);

    int countByUser(Integer userId);
    
    void deleteByUserId(Integer userId);

    List<UserCertificateEntity> findByUserId(Integer id);

	UserCertificateEntity findByUserIdAndTypeAndName(Integer userId, short type, String diploma);

	UserCertificate findOneByUserIdAndTypeAndName(Integer id, short i, String diploma);

	void deleteByUserIdAndTypeAndName(Integer id, short i, String diploma);
}
