/*
 * Created on 20 Mar 2017 ( Time 10:36:26 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.trams.hello.business.service;

import java.util.List;

import org.springframework.data.domain.Page;
import org.trams.hello.bean.UserPsychologicalFile;
import org.trams.hello.bean.api.PsychologicalTestSetting;
import org.trams.hello.bean.api.UserPsychologicalFileApi;
import org.trams.hello.bean.jpa.UserPsychologicalFileEntity;

/**
 * Business Service Interface for entity UserPsychologicalFile.
 */
public interface UserPsychologicalFileService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	UserPsychologicalFile findById( Integer id  ) ;

	/** 
	 * Loads all entities.
	 * @return all entities
	 */
	List<UserPsychologicalFile> findAll();
	
	/**
	 * Loads entities in page number.
	 * @return entities
	 */

	Page<UserPsychologicalFileEntity> findAll(Integer page);

	/**
	 * Count all entities
	 * @return Long
	 */
	Long countTotal();
	

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	UserPsychologicalFile save(UserPsychologicalFile entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	UserPsychologicalFile update(UserPsychologicalFile entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	UserPsychologicalFile create(UserPsychologicalFile entity);
	
	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete( Integer id );

	Page<UserPsychologicalFileEntity> listPaging(Integer page,Integer size);
	
	List<UserPsychologicalFileApi> listByRequestId(Integer reqId);
	
	List<UserPsychologicalFileApi> listByUserId(Integer userId);
	
	List<UserPsychologicalFileApi> listByUserIdAndPsyTestSetting(Integer userId, Integer testSettingId);
	
	List<UserPsychologicalFileApi> listByRequestPsychologicalIdInWebCouselor(Integer userId);
	
	List<PsychologicalTestSetting> listUserPsyTestIds(Integer userId);

}
