/*
 * Created on 10 thg 1 2017 ( Time 14:04:47 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.trams.hello.business.service;

import java.util.List;

import org.springframework.data.domain.Page;
import org.trams.hello.bean.UserReceiveMessage;
import org.trams.hello.bean.api.InboxMessage;
import org.trams.hello.bean.jpa.MessageEntity;
import org.trams.hello.bean.jpa.UserReceiveMessageEntity;

/**
 * Business Service Interface for entity UserReceiveMessage.
 */
public interface UserReceiveMessageService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	UserReceiveMessage findById( Integer id  ) ;

	/** 
	 * Loads all entities.
	 * @return all entities
	 */
	List<UserReceiveMessage> findAll();
	
	/**
	 * Loads entities in page number.
	 * @return entities
	 */

	Page<UserReceiveMessageEntity> findAll(Integer page);

	/**
	 * Count all entities
	 * @return Long
	 */
	Long countTotal();
	

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	UserReceiveMessage save(UserReceiveMessage entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	UserReceiveMessage update(UserReceiveMessage entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	UserReceiveMessage create(UserReceiveMessage entity);
	
	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete( Integer id );

	Page<UserReceiveMessageEntity> listPaging(Integer page,Integer size);

	/**
	 *
	 * @return
	 */
	Page<UserReceiveMessageEntity> filterByUser(Integer userId, Short[] statuses, Integer page, Integer size);
	
	List<InboxMessage> filterByUser(Integer userId);
	
	List<InboxMessage> listSentMessage(Integer userId);

	InboxMessage findByUserReceiMessageId(Integer userRecMessId, Integer userId);
	
	InboxMessage findByUserReceiMessageIdInApp(Integer userRecMessId, Integer userId);
	
	List<UserReceiveMessageEntity> listInboxMessByUserId(Integer userId);
	
	List<MessageEntity> listSendMessByUserId(Integer userId);
	
	void updateIsDeleteByMessageId(Integer id);
}
