/*
 * Created on 23 thg 12 2016 ( Time 14:27:41 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.trams.hello.rest.controller;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.annotation.Resource;

import org.springframework.data.domain.Page;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.ResponseStatus;
import org.trams.hello.business.service.UserQuestionaireService;
import org.trams.hello.rest.common.AbstractRestController;

/**
 * Spring MVC controller for 'Comment' management.
 */
@RequestMapping("/v1/public/comment")
@Controller
public class CommentRestController extends AbstractRestController{

	@Resource
	private UserQuestionaireService userQuestionaireService;

	@RequestMapping(value = "", method = RequestMethod.GET)
	@ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public HashMap<String, Object> filter(
			@RequestParam(value = "counselorId") Integer counselorId,
			@RequestParam(value = "page", defaultValue = "1") Integer page
	) {
		Float result = userQuestionaireService.totalPointCounsolerId(counselorId);
		Page<Object[]> commentEntities = userQuestionaireService.listCommentByCounselorId(counselorId, page, 30);
		List<Map<String, Object>> results = new ArrayList<>();
		for (int i = 0; i < commentEntities.getContent().size(); i++) {
			Object[] o = commentEntities.getContent().get(i);
			Map<String, Object> userCommentMap = new HashMap<>();
			userCommentMap.put("name", o[0]);
			userCommentMap.put("point", o[1]);
			userCommentMap.put("comment", o[2]);
			results.add(userCommentMap);
		}
		return SUCCESS(results);
	}
		

}



