/*
 * Created on 23 thg 12 2016 ( Time 14:27:41 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.trams.hello.rest.controller;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.annotation.Resource;
import javax.servlet.http.HttpServletRequest;

import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.trams.hello.bean.Faq;
import org.trams.hello.business.service.FaqService;
import org.trams.hello.business.service.UserService;
import org.trams.hello.rest.common.AbstractRestController;
/**
 * Spring MVC controller for 'Question' management.
 */
@RequestMapping("/v1/faq")
@Controller
public class FaqRestController extends AbstractRestController{

	@Resource
	private FaqService faqService;
	
	@Resource
	private UserService userService;
	
	@RequestMapping(value = "/list", method = RequestMethod.POST)
	@ResponseBody
	public HashMap<String, Object> getFaqs(HttpServletRequest httpRequest) {
		try {
			HashMap<String, Object> ret = new HashMap<String, Object>();
			List<Faq> list = faqService.listByIsShowAndType((short) 1);
			ret.put("faqs", list);
			return SUCCESS(ret);
		} catch (Exception e) {
			e.printStackTrace();
			return FAIL("HAVE ERROR: " + e);
		}
	}

	@RequestMapping(value = "/detail", method = RequestMethod.POST)
	@ResponseBody
	public HashMap<String, Object> getFaqDetail(@RequestParam Map<String, Object> params,HttpServletRequest httpRequest) {
		try {
			HashMap<String, Object> ret = new HashMap<String, Object>();
			Integer id = (Integer.valueOf(params.get("id").toString()));
			Faq detail = faqService.findById(id);
			detail.setViewCount(detail.getViewCount() + 1);
			detail = faqService.update(detail);
			ret.put("faqDetail", detail);
			return SUCCESS(ret);
		} catch (Exception e) {
			e.printStackTrace();
			return FAIL("HAVE ERROR: " + e);
		}
	}
	
}



