/*
 * Created on 28 Mar 2017 ( Time 17:34:27 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.trams.hello.business.service.mapping;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import org.trams.hello.bean.Inquiry;
import org.trams.hello.bean.jpa.InquiryEntity;
import org.trams.hello.bean.jpa.UserEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class InquiryServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public InquiryServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'InquiryEntity' to 'Inquiry'
	 * @param inquiryEntity
	 */
	public Inquiry mapInquiryEntityToInquiry(InquiryEntity inquiryEntity) {
		if(inquiryEntity == null) {
			return null;
		}

		//--- Generic mapping 
		Inquiry inquiry = map(inquiryEntity, Inquiry.class);

		//--- Link mapping ( link to User )
		if(inquiryEntity.getUser() != null) {
			inquiry.setAskUserId(inquiryEntity.getUser().getId());
		}
		return inquiry;
	}
	
	/**
	 * Mapping from 'Inquiry' to 'InquiryEntity'
	 * @param inquiry
	 * @param inquiryEntity
	 */
	public void mapInquiryToInquiryEntity(Inquiry inquiry, InquiryEntity inquiryEntity) {
		if(inquiry == null) {
			return;
		}

		//--- Generic mapping 
		map(inquiry, inquiryEntity);

		//--- Link mapping ( link : inquiry )
		if( hasLinkToUser(inquiry) ) {
			UserEntity user1 = new UserEntity();
			user1.setId( inquiry.getAskUserId() );
			inquiryEntity.setUser( user1 );
		} else {
			inquiryEntity.setUser( null );
		}

	}
	
	/**
	 * Verify that User id is valid.
	 * @param User User
	 * @return boolean
	 */
	private boolean hasLinkToUser(Inquiry inquiry) {
		if(inquiry.getAskUserId() != null) {
			return true;
		}
		return false;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}