/*
 * Created on 5 Apr 2017 ( Time 09:09:52 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.trams.hello.business.service.mapping;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import org.trams.hello.bean.PsychologicalTestSetting;
import org.trams.hello.bean.jpa.PsychologicalTestSettingEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class PsychologicalTestSettingServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public PsychologicalTestSettingServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'PsychologicalTestSettingEntity' to 'PsychologicalTestSetting'
	 * @param psychologicalTestSettingEntity
	 */
	public PsychologicalTestSetting mapPsychologicalTestSettingEntityToPsychologicalTestSetting(PsychologicalTestSettingEntity psychologicalTestSettingEntity) {
		if(psychologicalTestSettingEntity == null) {
			return null;
		}

		//--- Generic mapping 
		PsychologicalTestSetting psychologicalTestSetting = map(psychologicalTestSettingEntity, PsychologicalTestSetting.class);

		return psychologicalTestSetting;
	}
	
	/**
	 * Mapping from 'PsychologicalTestSetting' to 'PsychologicalTestSettingEntity'
	 * @param psychologicalTestSetting
	 * @param psychologicalTestSettingEntity
	 */
	public void mapPsychologicalTestSettingToPsychologicalTestSettingEntity(PsychologicalTestSetting psychologicalTestSetting, PsychologicalTestSettingEntity psychologicalTestSettingEntity) {
		if(psychologicalTestSetting == null) {
			return;
		}

		//--- Generic mapping 
		map(psychologicalTestSetting, psychologicalTestSettingEntity);

	}
	
	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}