/*
 * Created on 22 May 2017 ( Time 10:13:16 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.trams.hello.business.service.mapping;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import org.trams.hello.bean.PushNotification;
import org.trams.hello.bean.jpa.PushNotificationEntity;
import org.trams.hello.bean.jpa.UserEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class PushNotificationServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public PushNotificationServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'PushNotificationEntity' to 'PushNotification'
	 * @param pushNotificationEntity
	 */
	public PushNotification mapPushNotificationEntityToPushNotification(PushNotificationEntity pushNotificationEntity) {
		if(pushNotificationEntity == null) {
			return null;
		}

		//--- Generic mapping 
		PushNotification pushNotification = map(pushNotificationEntity, PushNotification.class);

		//--- Link mapping ( link to User )
		if(pushNotificationEntity.getUser() != null) {
			pushNotification.setAdminId(pushNotificationEntity.getUser().getId());
		}
		return pushNotification;
	}
	
	/**
	 * Mapping from 'PushNotification' to 'PushNotificationEntity'
	 * @param pushNotification
	 * @param pushNotificationEntity
	 */
	public void mapPushNotificationToPushNotificationEntity(PushNotification pushNotification, PushNotificationEntity pushNotificationEntity) {
		if(pushNotification == null) {
			return;
		}

		//--- Generic mapping 
		map(pushNotification, pushNotificationEntity);

		//--- Link mapping ( link : pushNotification )
		if( hasLinkToUser(pushNotification) ) {
			UserEntity user1 = new UserEntity();
			user1.setId( pushNotification.getAdminId() );
			pushNotificationEntity.setUser( user1 );
		} else {
			pushNotificationEntity.setUser( null );
		}

	}
	
	/**
	 * Verify that User id is valid.
	 * @param User User
	 * @return boolean
	 */
	private boolean hasLinkToUser(PushNotification pushNotification) {
		if(pushNotification.getAdminId() != null) {
			return true;
		}
		return false;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}