/*
 * Created on 1 thg 12 2016 ( Time 15:28:38 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.trams.hello.business.service.mapping;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import org.trams.hello.bean.UserRole;
import org.trams.hello.bean.jpa.UserRoleEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class UserRoleServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public UserRoleServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'UserRoleEntity' to 'UserRole'
	 * @param userRoleEntity
	 */
	public UserRole mapUserRoleEntityToUserRole(UserRoleEntity userRoleEntity) {
		if(userRoleEntity == null) {
			return null;
		}

		//--- Generic mapping 
		UserRole userRole = map(userRoleEntity, UserRole.class);

		return userRole;
	}
	
	/**
	 * Mapping from 'UserRole' to 'UserRoleEntity'
	 * @param userRole
	 * @param userRoleEntity
	 */
	public void mapUserRoleToUserRoleEntity(UserRole userRole, UserRoleEntity userRoleEntity) {
		if(userRole == null) {
			return;
		}

		//--- Generic mapping 
		map(userRole, userRoleEntity);

	}
	
	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}