/*
 * Created on 29 Apr 2017 ( Time 10:20:35 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package org.trams.hello.business.service.mapping;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import org.trams.hello.bean.UserCertificate;
import org.trams.hello.bean.jpa.UserCertificateEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class UserCertificateServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public UserCertificateServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'UserCertificateEntity' to 'UserCertificate'
	 * @param userCertificateEntity
	 */
	public UserCertificate mapUserCertificateEntityToUserCertificate(UserCertificateEntity userCertificateEntity) {
		if(userCertificateEntity == null) {
			return null;
		}

		//--- Generic mapping 
		UserCertificate userCertificate = map(userCertificateEntity, UserCertificate.class);

		return userCertificate;
	}
	
	/**
	 * Mapping from 'UserCertificate' to 'UserCertificateEntity'
	 * @param userCertificate
	 * @param userCertificateEntity
	 */
	public void mapUserCertificateToUserCertificateEntity(UserCertificate userCertificate, UserCertificateEntity userCertificateEntity) {
		if(userCertificate == null) {
			return;
		}

		//--- Generic mapping 
		map(userCertificate, userCertificateEntity);

	}
	
	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}